[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/update-password*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/change-password*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
